a = input ("a:")
b = input ("b:")
print ("Téglalap terület:", int(a) * int(b))
print ("Téglalap kerülete:", int(a)*2 + int(b)*2)
print ("a+b:", int(a) + int(b))
print ("a-b:", int(a) - int(b))
print ("a/b:", int(a) / int(b))